/*
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;
import org.eclipse.xtext.validation.NamesAreUniqueValidator;
import org.xtext.roqme.validation.RoQMEValidator;

@ComposedChecks(validators = {NamesAreUniqueValidator.class})
public abstract class AbstractMIRoNValidator extends RoQMEValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/miron/datatypes"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/miron/kernel"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/datatypes"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/kernel"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/expressions"));
		return result;
	}
	
}
