/*
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.scoping;

import org.xtext.roqme.scoping.RoQMEScopeProvider;

public abstract class AbstractMIRoNScopeProvider extends RoQMEScopeProvider {
}
