<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kernel" nsURI="https://robmosys.eu/miron/kernel" nsPrefix="miron.kernel">
  <eClassifiers xsi:type="ecore:EClass" name="VariationPoint" eSuperTypes="../../../roqme.metamodel/metamodel/datatypes/roqmedatatypes.ecore#//TypedVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//Binding"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BtBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xpath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insertionType" eType="#//InsertionTypeEnum"
        defaultValueLiteral="IN"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InsertionTypeEnum">
    <eLiterals name="IN"/>
    <eLiterals name="AFTER" value="1" literal="AFTER"/>
    <eLiterals name="BEFORE" value="2" literal="BEFORE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="../../../roqme.metamodel/metamodel/datatypes/roqmedatatypes.ecore#//Sentence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implies" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="ecore:EClass ../../../roqme.metamodel/metamodel/expressions/roqmeexpressions.ecore#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="../../../roqme.metamodel/metamodel/kernel/roqmekernel.ecore#//Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="ecore:EClass ../../../roqme.metamodel/metamodel/expressions/roqmeexpressions.ecore#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchBinding" eSuperTypes="#//Binding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterSetRepository"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
