/*
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.behaviortree.ide.contentassist.antlr.internal.InternalBehaviorTreeParser;
import org.xtext.behaviortree.services.BehaviorTreeGrammarAccess;

public class BehaviorTreeParser extends AbstractContentAssistParser {

	@Inject
	private BehaviorTreeGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalBehaviorTreeParser createParser() {
		InternalBehaviorTreeParser result = new InternalBehaviorTreeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTreeNodeAccess().getAlternatives(), "rule__TreeNode__Alternatives");
					put(grammarAccess.getSubtreeNodeAccess().getAlternatives(), "rule__SubtreeNode__Alternatives");
					put(grammarAccess.getControlNodeAccess().getAlternatives(), "rule__ControlNode__Alternatives");
					put(grammarAccess.getDecoratorNodeAccess().getAlternatives(), "rule__DecoratorNode__Alternatives");
					put(grammarAccess.getLeafNodeAccess().getAlternatives(), "rule__LeafNode__Alternatives");
					put(grammarAccess.getAbstractActionAccess().getAlternatives(), "rule__AbstractAction__Alternatives");
					put(grammarAccess.getBTModelAccess().getGroup(), "rule__BTModel__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getBehaviorTreeAccess().getGroup(), "rule__BehaviorTree__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getSubtreeAccess().getGroup(), "rule__Subtree__Group__0");
					put(grammarAccess.getSubtreePlusAccess().getGroup(), "rule__SubtreePlus__Group__0");
					put(grammarAccess.getSequenceAccess().getGroup(), "rule__Sequence__Group__0");
					put(grammarAccess.getSequenceStarAccess().getGroup(), "rule__SequenceStar__Group__0");
					put(grammarAccess.getFallbackAccess().getGroup(), "rule__Fallback__Group__0");
					put(grammarAccess.getFallbackStarAccess().getGroup(), "rule__FallbackStar__Group__0");
					put(grammarAccess.getParallelAccess().getGroup(), "rule__Parallel__Group__0");
					put(grammarAccess.getSwitchAccess().getGroup(), "rule__Switch__Group__0");
					put(grammarAccess.getForceSuccessAccess().getGroup(), "rule__ForceSuccess__Group__0");
					put(grammarAccess.getForceFailureAccess().getGroup(), "rule__ForceFailure__Group__0");
					put(grammarAccess.getRepeatAccess().getGroup(), "rule__Repeat__Group__0");
					put(grammarAccess.getInverterAccess().getGroup(), "rule__Inverter__Group__0");
					put(grammarAccess.getTimeoutAccess().getGroup(), "rule__Timeout__Group__0");
					put(grammarAccess.getRetryUntilSuccessAccess().getGroup(), "rule__RetryUntilSuccess__Group__0");
					put(grammarAccess.getBlackboardCheckDoubleAccess().getGroup(), "rule__BlackboardCheckDouble__Group__0");
					put(grammarAccess.getBlackboardCheckIntAccess().getGroup(), "rule__BlackboardCheckInt__Group__0");
					put(grammarAccess.getBlackboardCheckStringAccess().getGroup(), "rule__BlackboardCheckString__Group__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getAlwaysSuccessAccess().getGroup(), "rule__AlwaysSuccess__Group__0");
					put(grammarAccess.getAlwaysFailureAccess().getGroup(), "rule__AlwaysFailure__Group__0");
					put(grammarAccess.getSetBlackboardAccess().getGroup(), "rule__SetBlackboard__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getTreeNodesModelAccess().getGroup(), "rule__TreeNodesModel__Group__0");
					put(grammarAccess.getBTModelAccess().getMain_tree_to_executeAssignment_4(), "rule__BTModel__Main_tree_to_executeAssignment_4");
					put(grammarAccess.getBTModelAccess().getImportsAssignment_6(), "rule__BTModel__ImportsAssignment_6");
					put(grammarAccess.getBTModelAccess().getTreesAssignment_7_0(), "rule__BTModel__TreesAssignment_7_0");
					put(grammarAccess.getBTModelAccess().getNodesmodelAssignment_7_1(), "rule__BTModel__NodesmodelAssignment_7_1");
					put(grammarAccess.getImportAccess().getImportURIAssignment_4(), "rule__Import__ImportURIAssignment_4");
					put(grammarAccess.getBehaviorTreeAccess().getAttributesAssignment_2(), "rule__BehaviorTree__AttributesAssignment_2");
					put(grammarAccess.getBehaviorTreeAccess().getNodesAssignment_4(), "rule__BehaviorTree__NodesAssignment_4");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getValueAssignment_2(), "rule__Attribute__ValueAssignment_2");
					put(grammarAccess.getSubtreeAccess().getBehaviortreeAssignment_4(), "rule__Subtree__BehaviortreeAssignment_4");
					put(grammarAccess.getSubtreeAccess().getAttributesAssignment_5(), "rule__Subtree__AttributesAssignment_5");
					put(grammarAccess.getSubtreePlusAccess().getBehaviortreeAssignment_4(), "rule__SubtreePlus__BehaviortreeAssignment_4");
					put(grammarAccess.getSubtreePlusAccess().getAttributesAssignment_5(), "rule__SubtreePlus__AttributesAssignment_5");
					put(grammarAccess.getSequenceAccess().getAttributesAssignment_3(), "rule__Sequence__AttributesAssignment_3");
					put(grammarAccess.getSequenceAccess().getNodesAssignment_5(), "rule__Sequence__NodesAssignment_5");
					put(grammarAccess.getSequenceStarAccess().getAttributesAssignment_3(), "rule__SequenceStar__AttributesAssignment_3");
					put(grammarAccess.getSequenceStarAccess().getNodesAssignment_5(), "rule__SequenceStar__NodesAssignment_5");
					put(grammarAccess.getFallbackAccess().getAttributesAssignment_3(), "rule__Fallback__AttributesAssignment_3");
					put(grammarAccess.getFallbackAccess().getNodesAssignment_5(), "rule__Fallback__NodesAssignment_5");
					put(grammarAccess.getFallbackStarAccess().getAttributesAssignment_3(), "rule__FallbackStar__AttributesAssignment_3");
					put(grammarAccess.getFallbackStarAccess().getNodesAssignment_5(), "rule__FallbackStar__NodesAssignment_5");
					put(grammarAccess.getParallelAccess().getAttributesAssignment_3(), "rule__Parallel__AttributesAssignment_3");
					put(grammarAccess.getParallelAccess().getNodesAssignment_5(), "rule__Parallel__NodesAssignment_5");
					put(grammarAccess.getSwitchAccess().getAttributesAssignment_3(), "rule__Switch__AttributesAssignment_3");
					put(grammarAccess.getSwitchAccess().getNodesAssignment_5(), "rule__Switch__NodesAssignment_5");
					put(grammarAccess.getForceSuccessAccess().getAttributesAssignment_3(), "rule__ForceSuccess__AttributesAssignment_3");
					put(grammarAccess.getForceSuccessAccess().getNodeAssignment_5(), "rule__ForceSuccess__NodeAssignment_5");
					put(grammarAccess.getForceFailureAccess().getAttributesAssignment_3(), "rule__ForceFailure__AttributesAssignment_3");
					put(grammarAccess.getForceFailureAccess().getNodeAssignment_5(), "rule__ForceFailure__NodeAssignment_5");
					put(grammarAccess.getRepeatAccess().getAttributesAssignment_3(), "rule__Repeat__AttributesAssignment_3");
					put(grammarAccess.getRepeatAccess().getNodeAssignment_5(), "rule__Repeat__NodeAssignment_5");
					put(grammarAccess.getInverterAccess().getAttributesAssignment_3(), "rule__Inverter__AttributesAssignment_3");
					put(grammarAccess.getInverterAccess().getNodeAssignment_5(), "rule__Inverter__NodeAssignment_5");
					put(grammarAccess.getTimeoutAccess().getAttributesAssignment_3(), "rule__Timeout__AttributesAssignment_3");
					put(grammarAccess.getTimeoutAccess().getNodeAssignment_5(), "rule__Timeout__NodeAssignment_5");
					put(grammarAccess.getRetryUntilSuccessAccess().getAttributesAssignment_3(), "rule__RetryUntilSuccess__AttributesAssignment_3");
					put(grammarAccess.getRetryUntilSuccessAccess().getNodeAssignment_5(), "rule__RetryUntilSuccess__NodeAssignment_5");
					put(grammarAccess.getBlackboardCheckDoubleAccess().getAttributesAssignment_3(), "rule__BlackboardCheckDouble__AttributesAssignment_3");
					put(grammarAccess.getBlackboardCheckDoubleAccess().getNodeAssignment_5(), "rule__BlackboardCheckDouble__NodeAssignment_5");
					put(grammarAccess.getBlackboardCheckIntAccess().getAttributesAssignment_3(), "rule__BlackboardCheckInt__AttributesAssignment_3");
					put(grammarAccess.getBlackboardCheckIntAccess().getNodeAssignment_5(), "rule__BlackboardCheckInt__NodeAssignment_5");
					put(grammarAccess.getBlackboardCheckStringAccess().getAttributesAssignment_3(), "rule__BlackboardCheckString__AttributesAssignment_3");
					put(grammarAccess.getBlackboardCheckStringAccess().getNodeAssignment_5(), "rule__BlackboardCheckString__NodeAssignment_5");
					put(grammarAccess.getConditionAccess().getAttributesAssignment_3(), "rule__Condition__AttributesAssignment_3");
					put(grammarAccess.getAlwaysSuccessAccess().getAttributesAssignment_3(), "rule__AlwaysSuccess__AttributesAssignment_3");
					put(grammarAccess.getAlwaysFailureAccess().getAttributesAssignment_3(), "rule__AlwaysFailure__AttributesAssignment_3");
					put(grammarAccess.getSetBlackboardAccess().getAttributesAssignment_3(), "rule__SetBlackboard__AttributesAssignment_3");
					put(grammarAccess.getActionAccess().getAttributesAssignment_3(), "rule__Action__AttributesAssignment_3");
					put(grammarAccess.getTreeNodesModelAccess().getContentAssignment_1(), "rule__TreeNodesModel__ContentAssignment_1");
					put(grammarAccess.getBTModelAccess().getUnorderedGroup_7(), "rule__BTModel__UnorderedGroup_7");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BehaviorTreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BehaviorTreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
