/*
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.behaviortree.parser.antlr.internal.InternalBehaviorTreeParser;
import org.xtext.behaviortree.services.BehaviorTreeGrammarAccess;

public class BehaviorTreeParser extends AbstractAntlrParser {

	@Inject
	private BehaviorTreeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBehaviorTreeParser createParser(XtextTokenStream stream) {
		return new InternalBehaviorTreeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BTModel";
	}

	public BehaviorTreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BehaviorTreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
