/*
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BehaviorTreeStandaloneSetup extends BehaviorTreeStandaloneSetupGenerated {

	def static void doSetup() {
		new BehaviorTreeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
