/*
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.miron.MIRoNRuntimeModule
import org.xtext.miron.MIRoNStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MIRoNIdeSetup extends MIRoNStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MIRoNRuntimeModule, new MIRoNIdeModule))
	}
	
}
